name: Build opluslabs CICD

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build Static Files
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Write Environment Variables
        id: write_env
        run: |
          case "${{ github.ref }}" in
          refs/heads/develop)
          echo '
          ' > .env
          ;;
          refs/heads/main)
          echo '
          # Write Production Environment
          ' > .env
          ;;
          esac

      - name: Install dependencies
        run: yarn install

      - name: Generate build
        run: |
          yarn build

      - name: Upload Dist as Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'  }}
        with:
          name: ${{github.event.repository.name}}-${{ github.ref_name }}
          path: dist
          retention-days: 1

  deploy:
    name: Deploy static files
    needs:
      - build
    if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'  }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Get Artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
          name: ${{github.event.repository.name}}-${{ github.ref_name }}
      - name: Get VM SSH host and user
        id: get_vm_conf
        run: |
          case "${{ github.ref }}" in
          refs/heads/develop)
              export SERVER_IP=139.59.31.73
              export SERVER_USERNAME=root
              export PROJECT_PATH=/srv/projects/dev/${{github.event.repository.name}}/dist
              ;;      
              refs/heads/main)
              export SERVER_IP=139.59.31.73
              export SERVER_USERNAME=root
              export PROJECT_PATH=/srv/projects/prod/${{github.event.repository.name}}/dist
              ;;   
          esac
          echo "SERVER_IP=${SERVER_IP}" >> $GITHUB_OUTPUT
          echo "SERVER_USERNAME=${SERVER_USERNAME}" >> $GITHUB_OUTPUT
          echo "PROJECT_PATH=${PROJECT_PATH}" >> $GITHUB_OUTPUT

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan ${{ steps.get_vm_conf.outputs.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: copy static files
        run: |
          scp -r ./dist/* ${{ steps.get_vm_conf.outputs.SERVER_USERNAME }}@${{ steps.get_vm_conf.outputs.SERVER_IP }}:${{ steps.get_vm_conf.outputs.PROJECT_PATH }}
          echo "Build Pass"
